### ISSUE TITLE
Access control configuration

### ISSUE THREAD

**Issue by nusje2000** [nusje2000/feature-toggle-bundle#34]
Based on a solution mentioned in [this comment](https://github.com/nusje2000/feature-toggle-bundle/issues/33#issuecomment-874160983).

There should be a way of guarding routes via a configuration file. The definition of this configuration should look a bit like the way you define security access control within symfony:
```yaml
nusje2000_feature_toggle:
    access_control:
        - {path: ^/path-1, features: {feature_1: true}} # will only be accessible if feature_1 is enabled
        - {path: ^/path-2, features: {feature_2: false}} # will only be accessible if feature_2 is disabled
```
