### ISSUE TITLE
Ability to add a description to feature toggles

### ISSUE THREAD

**Issue by nusje2000** [nusje2000/feature-toggle-bundle#44]
When using the feature toggles it might be useful to have the ability to add metadata to a feature toggle to clarify the definition for the end user.

```yaml
nusje2000_feature_toggle:
    environment:
        features:
            feature_toggle_1: true
            feature_toggle_2: false
            feature_toggle_3:
                description: 'For human. By human.'
                value: false
```
